# Generated by Django 2.2.3 on 2019-07-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='tag1_a',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='tag2_a',
        ),
    ]
