# Generated by Django 2.2.3 on 2019-07-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='notice_a',
            field=models.TextField(default='', max_length=2200, verbose_name='Describe Answer'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title_a',
            field=models.CharField(max_length=150, verbose_name='Title of Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='notice_q',
            field=models.TextField(default='', max_length=1000, verbose_name='Description of Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_q',
            field=models.CharField(max_length=150, verbose_name='Title of Question'),
        ),
    ]
