# Generated by Django 2.2.3 on 2019-08-22 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190727_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
