# Generated by Django 2.2.3 on 2019-08-22 13:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_answer_upvoted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
