# Generated by Django 2.2.3 on 2019-08-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_downvoted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='title_a',
            field=models.CharField(max_length=50, verbose_name='Title of Answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_q',
            field=models.CharField(max_length=50, verbose_name='Title of Question'),
        ),
    ]
