# Generated by Django 2.2.5 on 2019-10-28 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_answer_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvoted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='downvoters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='upvoters', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='answer_views',
        ),
    ]
