# Generated by Django 2.2.5 on 2019-10-28 07:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_auto_20191028_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='downvoted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='downvoters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='upvoted_by',
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoters', to=settings.AUTH_USER_MODEL),
        ),
    ]
